- ffmpeg-sys-the-third/build.rs
The ffmpeg project changed their branch/tag naming structure. There is now a branch for the major.minor version using the old naming scheme (`release/{major}.{minor}`) and a tag called `n{major}.{minor}[.{patch}]`.
This change broke the static builds which checked out no-longer-existing ffmpeg branches with their old name.
> Fix broken static builds

- ffmpeg-sys-the-third/Cargo.toml
- ffmpeg-sys-the-third/build.rs
This patch upgrades the `bindgen` dependency to version 0.64 which includes a fix for an upstream issue broken builds when building w/ clang 16 or newer \[0\].
The use of a wildcard `*` was removed in bindgen 0.62 \[1\], code has been updated to use the regex approach instead to continue working.
\[0]: https://github.com/rust-lang/rust-bindgen/pull/2316
\[1]: https://github.com/rust-lang/rust-bindgen/issues/2373
> Fix build against clang 16

- examples/chapters.rs
- examples/dump-frames.rs
- examples/metadata.rs
- examples/transcode-x264.rs
- ffmpeg-sys-the-third/build.rs
pkg-config does not look for M1 homebrew paths by default:
```
$ pkg-config --variable pc_path pkg-config
/usr/local/Homebrew/lib/pkgconfig:/usr/local/Homebrew/share/pkgconfig:/usr/local/lib/pkgconfig:/usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/12
```
Causing the error below:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: `PKG_CONFIG_ALLOW_SYSTEM_CFLAGS="1" PKG_CONFIG_ALLOW_SYSTEM_LIBS="1" "pkg-config" "--libs" "--cflags" "libavutil"` did not exit successfully: exit status: 1
error: could not find system library 'libavutil' required by the 'ffmpeg-sys-the-third' crate
--- stderr
Package libavutil was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavutil.pc'
to the PKG_CONFIG_PATH …
```
> Add macOS package manager search paths for pkg-config

- examples/dump-frames.rs
- examples/remux.rs
- examples/transcode-audio.rs
- examples/transcode-x264.rs
- src/format/context/input.rs
The current behavior of the packet iterator is to silently skip errors. This makes it unusable with interrupt callbacks because the loop never terminates.
One solution is to break on `Error::Eof | Error::Exit`.
I think a cleaner solution is to make the iterator return a `Result`, like e.g. tokio streams do it. This patch does that.
The downside is that this is a semver-major change, although the fix in the clients is trivial if they want to keep ignoring errors (see the patch to examples). Another option would be to introduce `.packets2()` function that returns this iterator.
What I don't know is if ffmpeg can throw `EINTR` or any other restartable error here which we should always ignore. From glancing over the ffmpeg code it seems that protocols already retry `EINTR`. This is only a …
> Propagate errors in Input::packets().

- .github/workflows/build.yml
- src/codec/id.rs
- src/util/format/pixel.rs
I noticed that there are some new variants in 6.1.1, but this should fix 6.1.0 compilation.
Preferably merged after #15 so this is verified, it's a bit difficult to test with different FFmpeg versions locally.
> Add missing enum variants for FFmpeg 6.1

- src/filter/filter.rs
`avfilter_pad_count` still exists in 5.0 and beyond (renamed to `avfilter_filter_pad_count`), but it is unnecessary because `nb_outputs`/`nb_inputs` exists. The old code makes no sense at all (passing a pointer as `count` parameter).
CI should show that all tests < 5.0 pass.
> Fix PadIter in FFmpeg pre-5.0

- ffmpeg-sys-the-third/Cargo.toml
- ffmpeg-sys-the-third/build.rs
`std::thread::available_parallelism` is stable since Rust 1.59.0, so no MSRV concerns.
> Remove num_cpus build dependency

- ffmpeg-sys-the-third/build.rs
There are multiple small changes in this PR:
- new helper function `cargo_feature_enabled(feature)`
- move external libs to static list
- new trait to call `configure.switch(..)` and `configure.enable(..)`
> Refactor `fn build` in build script

- .github/workflows/build.yml
This was an oversight in the CI up until now.
The tests in bindings.rs are actually very important to guarantee that assumptions in Rust code are met. Unsafe code has a lot of requirements regarding alignment and such, and these tests verify them.
A shortened example showing `AVCodec` tests:
```rs
#[repr(C)]
#[derive(Debug /*, ... */)]
pub struct AVCodec {
pub name: *const libc::c_char,
// ...
}
```
```rs
#[test]
fn bindgen_test_layout_AVCodec() {
const UNINIT: ::std::mem::MaybeUninit<AVCodec> = ::std::mem::MaybeUninit::uninit();
let ptr = UNINIT.as_ptr();
assert_eq!(
::std::mem::size_of::<AVCodec>(),
104usize,
concat!("Size of: ", stringify!(AVCodec))
);
assert_eq!(
::std::mem::align_of::<AVCodec>(),
8usize,
concat!("Alignment of ", stringify!(AVCodec))
);
assert_eq!(
unsafe { …
```
> Run sys (bindgen) tests in CI

- ffmpeg-sys-the-third/build.rs
I noticed that quite a lot were missing. I assume they were kept up to date until 4.4, and then went back and diffed the `version.h` and `version_major.h` files `n4.4...n5.1.4`, `n5.1.4...n6.1.1`.
Now that I'm noticing all this upkeep, it might make sense to create a checklist for when a new FFmpeg major version is released.
> New FF_API_ flags

- ffmpeg-sys-the-third/build.rs
The high number of commits is for review's sake, they should probably be squashed if & when merging.
Having `search()`, `source()`, `output()` calls scattered around the script seems not great to me. It's pretty easy to have internal consistency when passing parameters to `build()` and other functions.
> Avoid using "static" functions in build script

- src/filter/graph.rs
Upstream got a bug report: zmwangx/rust-ffmpeg#177.
Properly support appending new `AVFilterInOut`s to the input/output lists instead of just rewriting the first element over and over.
Also add a proper `Drop` implementation.
Looks like macOS CI will keep on failing (until CI change) because it's downloading FFmpeg 7.0.
> Fix avfiltergraph input output

- .github/workflows/build.yml
homebrew has rudimentary version support by specifying `ffmpeg@4`, `ffmpeg@5` etc. No minor/patch versions AFAICT.
Also reduced the frequency of scheduled builds. Daily is just too much. Caches should stay alive for 7 days at least, so this should not cause problems regarding cache. Time and day are chosen semi-randomly (but moved away from midnight because that is a known hot time for CI jobs)
> Add CI matrix for macOS builds

- ffmpeg-sys-the-third/build.rs
- ffmpeg-sys-the-third/src/avutil/rational.rs
Just realized that CI doesn't run rustfmt or clippy on the sys project. Not high priority, but should be added at some point.
> sys: Fix clippy lints, run cargo fmt

- Cargo.lock.MSRV
The MSRV lockfile wasn't updated after #55 (which updated some dependencies). This PR just includes those changes to make the msrv job pass again (compatibility is not affected, just CI).
Note that `image` added a lot of dependencies (transitive `rav1e` dependency among others), so it might be worth disabling default features for it.
> Update MSRV lockfile

- src/format/format/input.rs
- src/format/format/mod.rs
- src/format/format/new_iter.rs
- src/format/format/output.rs
Addresses #46.
Naming should be fine? It's closer to the FFmpeg function names than to the Rust-side `Format` API. Could be renamed to e.g. `list_inputs`/`list_outputs`.
> Add new (4.0+) API for `av_[de]muxer_iterate`

- ffmpeg-sys-the-third/build.rs
- src/util/option/mod.rs
7.0 added `AV_OPT_TYPE_FLAG_ARRAY`, which is a bitfield flag. This means that we can't rely on `AVOptionType` being an enum in the Rust sense which actually makes this unsound.
There's a point to be made about whether a Rust-like enum makes any sort of sense for FFI bindings (vs a simple newtype for the underlying integer), but for now this is an immediate fix to this known case of UB.
> Make AVOptionType a bitfield/int wrapper

- .github/workflows/build.yml
It's preinstalled on GHA runners and [causes a CI warning](https://github.com/shssoichiro/ffmpeg-the-third/actions/runs/9128422452).
> Don't tell brew to install pkg-config

- ffmpeg-sys-the-third/src/avutil/channel_layout.rs
- src/util/channel_layout/channel_custom.rs
See #63. @jbeich This builds on my machine, but could you verify that the tests pass on an affected platform?
I'll try to add something to CI after this
> Don't assume that `c_char` is an `i8`

- src/util/error.rs
Simply remove all the libc reexports. Fixes #66. 
Not 100% sure this is the best solution, but might be okay to bundle this with other breaking changes if/when they come.
> Remove libc error reexports

- build.rs
- ffmpeg-sys-the-third/build.rs
See #58. This change does not fix all warnings, but most of them.
I'm not sure how other `-sys` crates handle this..
> Add `rustc-check-cfg` for `ffmpeg_x_y` features

- ffmpeg-sys-the-third/build.rs
- src/codec/encoder/video.rs
- src/codec/id.rs
- src/util/format/pixel.rs
Addresses #36. Lot of pre-4.0 stuff got removed.
BTW: The rustc change about unexpected cfg values really showed its worth here. After removing those lines from `build.rs`, it immediately started showing warnings for unexpected feature flags. Updating the crate was as easy as deleting all lines with a warning.
It probably makes sense to go through the new FF_API flags on each release and check what they "gate", and incorporate that into the crate. That would make removing these features later a lot easier.
> Remove old FF_API_* features

- src/device/input.rs
- src/device/output.rs
- src/format/context/input.rs
- src/format/context/output.rs
- src/format/format/input.rs
- src/format/format/iter.rs
- src/format/format/output.rs
- src/format/mod.rs
- src/lib.rs
- Replace `wrap(*const/mut T) -> Self` with `from_raw(*const/mut T) -> Option<Self>`
- Use `NonNull` ptr internally
- Avoid using `*mut` if only `*const` is required
Also make `Input` and `Output` derive `Copy`. These types are basically pointers with helper functions, and both `AVInputFormat`s and `AVOutputFormat`s returned by FFmpeg are always static (in both the Rust and C sense), similar to `AVCodec`. So they are immutable (and should not even have an `fn as_mut_ptr`) and it's unproblematic to copy the pointers wherever needed.
To achieve this immutability, at least across the crate API, I removed the `register_*` API which was deprecated (and made nearly a noop) in 4.0 and removed in 5.0. This is a breaking change, see `src/lib.rs` and `src/format/mod.rs`.
> Refactor format::{Input, Output}

- .github/workflows/build.yml
- src/codec/config.rs
Reasoning: See https://github.com/jrottenberg/ffmpeg/issues/410 and the PR linked there. TL;DR: An update to the docker images (which was done from a PR branch, not documented and can't be found anywhere on `main`) broke our CI & the one response I *have* gotten has not been reassuring.
Since the problem is effectively a showstopper for this repo, let's switch to something that shouldn't break so easily, even if it's a bit more work to set up initially.
Changes:
- Replace jrottenberg/ffmpeg docker container with prebuilt binaries from https://github.com/wang-bin/avbuild
- This needs a bit of patching due to an [issue in the pkgconfig files](https://github.com/wang-bin/avbuild/issues/76)
- otherwise, just extract to some directory and then set `PKG_CONFIG_PATH` for compile time and …
> CI: Avoid docker containers in favor of prebuilt binaries

- examples/chapters.rs
- examples/dump-frames.rs
- examples/metadata.rs
- examples/transcode-audio.rs
- src/format/format/output.rs
- src/format/mod.rs
Doesn't really make sense to require a reference for these params, as both `String` and `&str` (etc.) implement `AsRef<Path>`.
This is breaking.
> Don't pass `AsRef<T>` params by reference

- .github/workflows/build.yml
Followup to #83. In a [very nice move](https://github.com/wang-bin/avbuild/issues/76#issuecomment-2464584408), the older binary packages were updated to include fixes to the pkgconfig files from the start, making the patches unnecessary.
> ci: Remove unnecessary pkgconfig patches

- examples/remux.rs
- examples/transcode-audio.rs
- examples/transcode-x264.rs
- src/as_ptr.rs
- src/codec/context.rs
- src/codec/mod.rs
- src/codec/parameters/borrowed.rs
- src/codec/parameters/borrowed_mut.rs
- src/codec/parameters/common.rs
- src/codec/parameters/mod.rs
- src/codec/parameters/owned.rs
- src/format/stream/stream.rs
- src/format/stream/stream_mut.rs
- src/lib.rs
- src/macros.rs
Currently, `Parameters` tries to differentiate its states (owned, shared) by setting the `owner` field. With the way the API works at the moment, there really isn't any advantage to this over using different structs for owned, shared, and mutable shared states. It takes up an extra `Rc` and complicates the differentiation between immutable and mutable borrows (since it's all the same type).
I'm also pretty sure that there is some potential for nasty UB via `Stream::parameters` because the returned `Parameters` type can be accessed mutably[^1] even though `Stream` is supposed to be an immutable reference to `AVStream`.
Some notes regarding the new implementation:
- I want to use the pattern `Something` (owned), `SomethingRef`, `SomethingMut` for other wrapper types in the future
- I don't …
> Refactor `codec::Parameters`

- src/codec/traits.rs
- src/lib.rs
`needless_lifetimes` seems to have been stabilized in 1.83. It correctly identifies completely unnecessary lifetimes, but also warns on cases like this:
```rs
warning: the following explicit lifetimes could be elided: 'a
--> src/software/scaling/vector.rs:32:6
|
32 | impl<'a> Vector<'a> {
|      ^^         ^^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_lifetimes
help: elide the lifetimes
|
32 - impl<'a> Vector<'a> {
32 + impl Vector<'_> {
```
I don't think this is an improvement, so unless https://github.com/rust-lang/rust-clippy/issues/13514 or something similar is done, I'd just `#![allow]` it.
> Fix clippy `needless_lifetimes` lint

- src/codec/codec.rs
They don't have specialized impl blocks yet, but this should at least allow differentiating between the different codec types.
Also moved the `is_video()` and `video()` (= `as_video()`) functions from `impl<T> Codec<T>` into `impl Codec<UnknownType>` because it's really only useful for codecs with an unknown type.
> Add remaining codec media types

- src/codec/codec.rs
- src/codec/config.rs
- src/iters.rs
- src/lib.rs
Small reorganization, could be useful for bigger changes later on.
Non-breaking change as everything changed is pub(crate) at most.
> Create crate-wide `iters` module

- .github/workflows/build.yml
- ffmpeg-sys-the-third/src/lib.rs
- src/codec/codec.rs
- src/codec/config.rs
- src/codec/decoder/audio.rs
- src/codec/encoder/audio.rs
- src/codec/packet/borrow.rs
- src/codec/packet/packet.rs
- src/codec/parameters/common.rs
- src/codec/subtitle/mod.rs
- src/device/extensions.rs
- src/filter/filter.rs
- src/filter/graph.rs
- src/format/chapter/chapter.rs
- src/format/chapter/chapter_mut.rs
- src/format/context/common.rs
- src/format/context/input.rs
- src/format/context/output.rs
- src/format/stream/stream.rs
- src/format/stream/stream_mut.rs
- src/software/scaling/filter.rs
- src/util/dictionary/immutable.rs
- src/util/frame/audio.rs
- src/util/frame/mod.rs
- src/util/frame/side_data.rs
The pointer comparison lint is valid and the `PartialEq`/`Eq` derives should probably be removed with the next major patch. I'd assume the derives are generally unused and API users would be surprised by this if they do use equality checks.
The lifetime change could be resolved in a few ways:
```rust
struct SomeType<'a> {}
pub fn rates(&self) -> SomeType {}
```
could turn into
```rust
pub fn rates(&'a self) -> SomeType<'a> {}
```
or
```rust
pub fn rates(&self) -> SomeType<'_> {}
```
or
```rust
pub fn rates(&'_ self) -> SomeType<'_> {}
```
I think the first two are acceptable and I just decided on option #2.
> Fix/ignore newer CI errors
